---
- name: create configuration directory
  file:
    path: /etc/docker/nginx
    state: directory
    recurse: yes

- name: create load_balancer
  template:
    src: load_balancer.j2
    dest: /etc/docker/nginx/load_balancer
