---
- name: recreate docker container
  docker_container:
    name: nginx
    image: jedi/nginx
    state: started
    recreate: yes
    networks:
      - name: '{{ docker_network }}'
    ports:
      - '80:80'
    volumes:
      - '/etc/docker/nginx:/etc/nginx/sites-enabled:ro'
