---
- name: reload docker container
  docker:
    name: nginx
    image: jedi/nginx
    state: reloaded
    net: jedi_nw
    ports:
      - '80:80'
    volumes:
      - '/etc/docker/nginx:/etc/nginx/sites-enabled:ro'
