---
- name: create data directory
  file:
    path: /var/docker/influxdb
    state: directory
    recurse: yes

- name: reload docker container
  docker:
    name: influxdb
    image: jedi/influxdb
    state: reloaded
    net: jedi_nw
    ports:
      - '8083:8083'
      - '8086:8086'
    volumes:
      - '/var/docker/influxdb:/var/lib/influxdb'
