---
- name: common
  hosts:
    - all
  roles:
    - common
  tags:
    - common

- name: install-docker
  hosts:
    - all
  roles:
    - docker
  tags:
    - docker

- name: clone-docker
  hosts:
    - all
  roles:
    - clone
  tags:
    - clone

- name: nginx-docker
  hosts:
    - all
  roles:
    - nginx
  tags:
    - nginx

- name: influxdb-docker
  hosts:
    - all
  roles:
    - influxdb
  tags:
    - influxdb

- name: telegraf-docker
  hosts:
    - all
  roles:
    - telegraf
  tags:
    - telegraf

- name: chronograf-docker
  hosts:
    - all
  roles:
    - chronograf
  tags:
    - chronograf
