---
- name: common
  hosts:
    - jedi
  roles:
    - common
  tags:
    - common

- name: docker
  hosts:
    - jedi
  roles:
    - docker
  tags:
    - docker

- name: clone
  hosts:
    - jedi
  roles:
    - clone
  tags:
    - clone

- name: nginx
  hosts:
    - jedi
  roles:
    - nginx
  tags:
    - nginx

- name: influxdb
  hosts:
    - jedi
  roles:
    - influxdb
  tags:
    - influxdb

- name: telegraf
  hosts:
    - jedi
  roles:
    - telegraf
  tags:
    - telegraf

- name: chronograf
  hosts:
    - jedi
  roles:
    - chronograf
  tags:
    - chronograf
