---
- name: create configuration directory
  file:
    path: /etc/docker/clone
    state: directory
    recurse: yes

- name: copy default
  copy:
    src: default
    dest: /etc/docker/clone/default
