---
- name: reload docker container {{ item }}
  docker:
    name: clone-{{ item }}
    image: jedi/clone
    state: reloaded
    net: '{{docker_network}}'
    volumes:
      - '/etc/docker/clone:/etc/nginx/sites-enabled:ro'
      - '/var/docker/clone-{{ item }}:/var/www/html:ro'
