---
- name: reload docker container {{item}}
  docker:
    name: clone-{{item}}
    image: jedi/clone
    state: reloaded
    net: jedi_nw
    volumes:
      - '/var/docker/clone-{{item}}:/var/www/html:ro'
