---
- name: create context directory
  file:
    path: /tmp/docker/clone
    state: directory
    recurse: yes

- name: copy dockerfile
  copy:
    src: Dockerfile
    dest: /tmp/docker/clone/Dockerfile

- name: build docker image
  docker_image:
    path: /tmp/docker/clone
    name: jedi/clone
