---
- name: create document root {{ item }}
  file:
    path: /var/docker/clone-{{ item }}
    state: directory
    recurse: yes

- name: create index.html {{ item }}
  template:
    src: index.html.j2
    dest: /var/docker/clone-{{ item }}/index.html
