---
- name: create document root
  file:
    path: /tmp/docker/clone-{{item}}
    state: directory
    recurse: yes

- name: copy index.html
  template:
    src: index.html.j2
    dest: /tmp/docker/clone-{{item}}/index.html
