---
- include: hostname.yml
  become: yes
  tags: common_hostname

- include: apt.yml
  become: yes
  tags: common_apt

- include: ssh.yml
  become: yes
  tags: common_ssh

- include: ufw.yml
  become: yes
  tags: common_ufw
