---
- name: create data directory
  file:
    path: /var/docker/chronograf
    state: directory
    recurse: yes

- name: recreate docker container
  docker_container:
    name: chronograf
    image: chronograf
    state: started
    recreate: yes
    networks:
      - name: '{{ docker_network }}'
    ports:
      - '10000:10000'
    volumes:
      - '/var/docker/chronograf:/var/lib/chronograf'
