---
- name: get kernel release
  command: uname -r
  register: uname_r

- name: install apt-transport-https
  apt:
    name: apt-transport-https

- name: install ca-certificates
  apt:
    name: ca-certificates

- name: install recommended package
  apt:
    name: linux-image-extra-{{ uname_r.stdout }}

- name: add new gpg key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: create docker.list
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  register: docker_list

- name: update apt package index
  apt:
    update_cache: yes
  when: docker_list|changed
