---
- name: recreate docker container {{ item }}
  docker_container:
    name: telegraf-{{ item }}
    image: telegraf
    state: started
    recreate: yes
    networks:
      - name: '{{ docker_network }}'
    volumes:
      - '/etc/docker/telegraf-{{ item }}:/etc/telegraf:ro'
