---
- name: reload docker container {{ item }}
  docker:
    name: telegraf-{{ item }}
    image: telegraf
    state: reloaded
    net: '{{docker_network}}'
    volumes:
      - '/etc/docker/telegraf-{{ item }}:/etc/telegraf:ro'
